### ISSUE TITLE
Provide a way for users to easily create secrets

### ISSUE THREAD

**Issue by francardoso93** [nearform/initium#22]
As we discussed, those shouldn't be replicated through different environments

**Comment by francardoso93** [comment]
Options discussed:
- k8s dashboard (Hosted in cluster)
- External secrets operator
- Develop our own UI
- New CLI commands 

Last one seems to be the best

**Comment by mablanco** [comment]
Work on the chosen option will follow in https://github.com/nearform/initium-cli/issues/146
