### ISSUE TITLE
quick-start guide based on an old version of cli

### ISSUE THREAD

**Issue by LucaLanziani** [nearform/initium#5]
The current [quick-start](https://github.com/nearform/initium/blob/master/quick-start.md) contains broken command and can be improved by reducing number of steps.

eg. the ngrok command requires the user to do an extra step to get the api-server port `kubectl cluster-info`

The cluster api endpoint can be printed with:

```
kubectl config view -o jsonpath='{.clusters[?(@.name == "kind-initium-platform")].cluster.server}' 
```

**Comment by spchortis** [comment]
Quick start guide was updated by [this](https://github.com/nearform/initium/pull/13) one.
